version: '3'
services:
  composer:
    image: composer:1.10.8
    volumes:
      - .:/app
    working_dir: /app
  php74:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
  php80:
    image: registry.gitlab.com/grahamcampbell/php:8.0
    volumes:
      - .:/app
    working_dir: /app
